# Site settings
title: frontfish.net
email: chris@frontfish.net
description: "Hi there. I'm Christopher Hinstorff, but you can call me Chris. I make 2D web games."
baseurl: ""
url: "http://frontfish.net"

footer_text: "© Christopher Hinstorff 2014"

github: chinstorff

# Build settings
markdown: kramdown
permalink: /:categories/:title

JB:
  comments:
    provider: disqus
    disqus:
      short_name: 'frontfish'
      
  analytics:
    provider: google
    google:
      tracking_id : 'UA-46595226-1'
 
gems:
  - jekyll-redirect-from